"""add language to posts

Revision ID: 664df0e30419
Revises: 890052e5b09d
Create Date: 2018-08-29 13:53:00.968189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664df0e30419'
down_revision = '890052e5b09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
